Enhance C++ Libraries: enh::WeightedField< integral, field_c > Class Template Reference
enh::WeightedField< integral, field_c > Class Template Reference
Class to represent number distributed in many weighted fields.
#include <WeightedField.enh.h>
Public Types
using value_type = integral
The underlying value type used.
Public Member Functions
constexpr void setRawValue (value_type val) noexcept
Sets the raw value (compounded weighted sum)
constexpr void setWeights (std::array< unsigned, weightCount > weight) noexcept
Sets weights to given weights.
constexpr void setValue (const std::array< value_type, fieldCount > &val) noexcept
Sets value to compounded weighted sum of given values.
constexpr void setValue (std::array< value_type, fieldCount > val, std::array< unsigned, weightCount > weight) noexcept
Sets weights and value.
constexpr WeightedField () noexcept
Constructs with initial value 0 and decade weights.
constexpr WeightedField (value_type val) noexcept
Constructs with initial value as parameter and decade weights.
constexpr WeightedField (value_type val, std::array< unsigned, weightCount > weight)
Constructs with initial value given and weights provided.
constexpr WeightedField (std::array< unsigned, weightCount > weight) noexcept
Constructs with initial value 0 and weights provided.
constexpr WeightedField (std::array< value_type, fieldCount > val, std::array< unsigned, weightCount > weight) noexcept
Constructs with initial value as weighted sum of first parameter and weights given.
constexpr value_type getRaw () const noexcept
Returns the raw Value.
constexpr unsigned getWeights (unsigned short value) const noexcept
Returns weight of value'th field with respect to last field.
constexpr unsigned long getAbsoluteWeights (unsigned short value) const noexcept
Returns The absolute (compounded) weight of a field.
constexpr const auto & getWeights () const noexcept
Returns The relative weights as an array.
constexpr auto getAbsoluteWeights () const noexcept
Returns The absolute weights as an array.
constexpr unsigned getFields (unsigned short value) const noexcept
Get the value of certian field.
constexpr WeightedField< value_type, fieldCount > add (value_type val) const noexcept
Returns sum of raw value and current object.
constexpr WeightedField< value_type, fieldCount > & saveAdd (value_type val) noexcept
Adds raw value to current objects.
constexpr WeightedField< value_type, fieldCount > & operator+= (value_type rhs)
operator overloaded to add and save.
constexpr WeightedField< value_type, fieldCount > add (const WeightedField< value_type, fieldCount > &rhs) const
Returns sum of current object and parameter.
constexpr WeightedField< value_type, fieldCount > & saveAdd (const WeightedField< value_type, fieldCount > &rhs)
Adds parameter to current object.
constexpr WeightedField< value_type, fieldCount > & operator+= (const WeightedField< value_type, fieldCount > &rhs)
Adds parameter to current object.
constexpr WeightedField< value_type, fieldCount > sub (value_type val) const noexcept
Returns difference of raw value and current object.
constexpr WeightedField< value_type, fieldCount > & saveSub (value_type val) noexcept
Returns difference of raw value and current object.
constexpr WeightedField< value_type, fieldCount > & operator-= (value_type rhs)
operator overloaded to subtract and save.
constexpr WeightedField< value_type, fieldCount > sub (const WeightedField< value_type, fieldCount > &rhs) const
Returns sum of current object and parameter.
constexpr WeightedField< value_type, fieldCount > & saveSub (const WeightedField< value_type, fieldCount > &rhs)
subtracts parameter from object.
constexpr WeightedField< value_type, fieldCount > & operator-= (const WeightedField< value_type, fieldCount > &rhs)
subtracts parameter from object.
constexpr WeightedField< value_type, fieldCount > subu (value_type val, value_type type_max=std::numeric_limits< value_type >::max()) const noexcept
Returns difference with no overflow or underflow.
constexpr WeightedField< value_type, fieldCount > & saveSubu (value_type val, value_type type_max=std::numeric_limits< value_type >::max()) noexcept
subtracts parameter with no overflow or underflow.
constexpr WeightedField< value_type, fieldCount > addu (value_type val, value_type type_max=std::numeric_limits< value_type >::max()) const noexcept
Returns sum with no overflow or underflow.
constexpr WeightedField< value_type, fieldCount > & saveAddu (value_type val, value_type type_max=std::numeric_limits< value_type >::max()) noexcept
Adds parameter to object with no overflow or underflow.
constexpr WeightedField< value_type, fieldCount > addu (const WeightedField< value_type, fieldCount > &rhs, value_type type_max=std::numeric_limits< value_type >::max()) const
Returns sum with no overflow or underflow.
constexpr WeightedField< value_type, fieldCount > & saveAddu (const WeightedField< value_type, fieldCount > &rhs, value_type type_max=std::numeric_limits< value_type >::max())
Adds parameter to object with no overflow or underflow.
constexpr WeightedField< value_type, fieldCount > subu (const WeightedField< value_type, fieldCount > &rhs, value_type type_max=std::numeric_limits< value_type >::max()) const
Returns difference with no overflow or underflow.
constexpr WeightedField< value_type, fieldCount > & saveSubu (const WeightedField< value_type, fieldCount > &rhs, value_type type_max=std::numeric_limits< value_type >::max())
subtracts parameter with no overflow or underflow.
constexpr WeightedField< value_type, fieldCount > mult (value_type multiplier) const noexcept
Returns product of current object and value with a weight of 1.
constexpr WeightedField< value_type, fieldCount > & saveMult (value_type multiplier) noexcept
multiplies current object with value with a weight of 1.
constexpr WeightedField< value_type, fieldCount > & operator*= (value_type multiplier) noexcept
multiplies current object with value with a weight of 1.
constexpr WeightedField< value_type, fieldCount > div (value_type divisor) const
Returns quotient of current object devided by value with a weight of 1.
constexpr WeightedField< value_type, fieldCount > & saveDiv (value_type divisor)
Sets current object to quotient of current object devided by value with a weight of 1.
constexpr WeightedField< value_type, fieldCount > & operator/= (value_type divisor)
Sets current object to quotient of current object devided by value with a weight of 1.
constexpr bool operator< (value_type val) const noexcept
Checks whether object is less than parameter.
constexpr bool operator< (const WeightedField< value_type, fieldCount > &rhs) const
Checks whether object is less than parameter.
constexpr bool operator<= (value_type val) const noexcept
Checks whether object is less than or equal to parameter.
constexpr bool operator<= (const WeightedField< value_type, fieldCount > &rhs) const
Checks whether object is less than or equal to parameter.
constexpr bool operator> (value_type val) const noexcept
Checks whether object is greater than parameter.
constexpr bool operator> (const WeightedField< value_type, fieldCount > &rhs) const
Checks whether object is greater than parameter.
constexpr bool operator>= (value_type val) const noexcept
Checks whether object is greater than or equal to parameter.
constexpr bool operator>= (const WeightedField< value_type, fieldCount > &rhs) const
Checks whether object is greater than or equal to parameter.
constexpr bool operator== (value_type val) const noexcept
Checks whether object is equal to parameter.
constexpr bool operator== (const WeightedField< value_type, fieldCount > &rhs) const noexcept
Checks whether object is equal to parameter.
constexpr bool operator!= (value_type val) const noexcept
Checks whether object is not equal to parameter.
constexpr bool operator!= (const WeightedField< value_type, fieldCount > &rhs) const noexcept
Checks whether object is not equal to parameter.
constexpr bool isSameWeights (const WeightedField< value_type, fieldCount > &rhs) const noexcept
Checks if weights are same.
Static Public Attributes
constexpr static unsigned fieldCount = field_c
The number of fields present.
constexpr static unsigned weightCount = field_c - 1
The number of weights, not including first (implied 1).
Detailed Description
template<class integral, unsigned field_c>
class enh::WeightedField< integral, field_c >
Class to represent number distributed in many weighted fields.
template
integral : The underlying type to store data.
unsigned field_c : The Number of weighted fields.
Constructor & Destructor Documentation
WeightedField() [1/4]
template<class integral , unsigned field_c> constexpr enh::WeightedField< integral, field_c >::WeightedField (value_type val) inline explicit constexpr noexcept
Constructs with initial value as parameter and decade weights.
Parameters
val : in : The initial value of the object.
WeightedField() [2/4]
template<class integral , unsigned field_c> constexpr enh::WeightedField< integral, field_c >::WeightedField (value_type val, std::array< unsigned, weightCount > weight) inline constexpr
Constructs with initial value given and weights provided.
Throws std::invalid_argument if invalid weights are provided.
Parameters
val : in : The initial value of the object.
weight : in : The weights to be set (index 0 is the lowest level after implicit weight 1.
WeightedField() [3/4]
template<class integral , unsigned field_c> constexpr enh::WeightedField< integral, field_c >::WeightedField (std::array< unsigned, weightCount > weight) inline explicit constexpr noexcept
Constructs with initial value 0 and weights provided.
Throws std::invalid_argument if invalid weights are provided.
Parameters
weight : in : The weights to be set (index 0 is the lowest level after implicit weight 1.
WeightedField() [4/4]
template<class integral , unsigned field_c> constexpr enh::WeightedField< integral, field_c >::WeightedField (std::array< value_type, fieldCount > val, std::array< unsigned, weightCount > weight) inline constexpr noexcept
Constructs with initial value as weighted sum of first parameter and weights given.
Throws std::invalid_argument if invalid weights are provided.
Parameters
val : in : The values of each field as an array.
weight : in : The weights to be set (index 0 is the lowest level after implicit weight 1.
Member Function Documentation
add() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::add (const WeightedField< value_type, fieldCount > & rhs) const inline constexpr
Returns sum of current object and parameter.
Return
Sum of current object and paramater.
Exception
Throws if weights are not same.
Parameters
rhs : in : The object to be added.
References enh::WeightedField< integral, field_c >::add(), enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::weightCount.
add() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::add (value_type val) const inline constexpr noexcept
Returns sum of raw value and current object.
Return
Returns the sum.
Parameters
val : in : The value to be added.
References enh::WeightedField< integral, field_c >::getRaw().
addu() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::addu (const WeightedField< value_type, fieldCount > & rhs, value_type type_max = std::numeric_limits<value_type>::max()) const inline constexpr
Returns sum with no overflow or underflow.
Return
The sum of current object and parameter.
Parameters
rhs : in : The value to be added.
type_max : in : The maximum value for the value_type.
References enh::WeightedField< integral, field_c >::addu(), enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::weightCount.
addu() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::addu (value_type val, value_type type_max = std::numeric_limits<value_type>::max()) const inline constexpr noexcept
Returns sum with no overflow or underflow.
Return
The sum of current object and parameter.
Parameters
val : in : The value to be added.
type_max : in : The maximum value for the value_type.
References enh::WeightedField< integral, field_c >::add(), enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::subu().
div()
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::div (value_type divisor) const inline constexpr
Returns quotient of current object devided by value with a weight of 1.
Return
Returns the quotient of current object devided by divisor.
Parameters
divisor : in : The number to be divided by.
References enh::WeightedField< integral, field_c >::getRaw().
getAbsoluteWeights() [1/2]
template<class integral , unsigned field_c> constexpr auto enh::WeightedField< integral, field_c >::getAbsoluteWeights () const inline constexpr noexcept
Returns The absolute weights as an array.
Return
Returns the absolute weights as an array.
References enh::WeightedField< integral, field_c >::weightCount.
getAbsoluteWeights() [2/2]
template<class integral , unsigned field_c> constexpr unsigned long enh::WeightedField< integral, field_c >::getAbsoluteWeights (unsigned short value) const inline constexpr noexcept
Returns The absolute (compounded) weight of a field.
Return
(relative to lowest field with absolute weight of 1).
Parameters
value : in : The index of field.
References enh::WeightedField< integral, field_c >::fieldCount.
getFields()
template<class integral , unsigned field_c> constexpr unsigned enh::WeightedField< integral, field_c >::getFields (unsigned short value) const inline constexpr noexcept
Get the value of certian field.
Parameters
value : in : The index of the field.
References enh::WeightedField< integral, field_c >::getAbsoluteWeights(), enh::WeightedField< integral, field_c >::getWeights(), and enh::WeightedField< integral, field_c >::weightCount.
getRaw()
template<class integral , unsigned field_c> constexpr value_type enh::WeightedField< integral, field_c >::getRaw () const inline constexpr noexcept
Returns the raw Value.
Return
Returns the raw Value (compounded weighted sum of all fields).
getWeights() [1/2]
template<class integral , unsigned field_c> constexpr const auto& enh::WeightedField< integral, field_c >::getWeights () const inline constexpr noexcept
Returns The relative weights as an array.
Return
Returns the relative weights as an const reference to an array.
getWeights() [2/2]
template<class integral , unsigned field_c> constexpr unsigned enh::WeightedField< integral, field_c >::getWeights (unsigned short value) const inline constexpr noexcept
Returns weight of value'th field with respect to last field.
Return
Returns the relative weight associated with that field.
References enh::WeightedField< integral, field_c >::fieldCount.
isSameWeights()
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::isSameWeights (const WeightedField< value_type, fieldCount > & rhs) const inline constexpr noexcept
Checks if weights are same.
Return
Returns true if weights are same.
Parameters
rhs : in : Value to compare with.
References enh::WeightedField< integral, field_c >::weightCount.
mult()
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::mult (value_type multiplier) const inline constexpr noexcept
Returns product of current object and value with a weight of 1.
Return
Returns the product of multiplier and raw Value.
Parameters
multiplier : in : The number to be multiplied by.
References enh::WeightedField< integral, field_c >::getRaw().
operator!=() [1/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator!= (const WeightedField< value_type, fieldCount > & rhs) const inline constexpr noexcept
Checks whether object is not equal to parameter.
Weights is checked as well.
Return
True if lhs equal to rhs.
Parameters
rhs : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::weightCount.
operator!=() [2/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator!= (value_type val) const inline constexpr noexcept
Checks whether object is not equal to parameter.
Weights is checked as well.
Return
True if lhs equal to rhs.
Parameters
val : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw().
operator*=()
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::operator*= (value_type multiplier) inline constexpr noexcept
multiplies current object with value with a weight of 1.
Return
Returns reference to current objects.
Parameters
multiplier : in : The number to be multiplied by.
References enh::WeightedField< integral, field_c >::saveMult().
operator+=() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::operator+= (const WeightedField< value_type, fieldCount > & rhs) inline constexpr
Adds parameter to current object.
Return
Reference to current object.
Exception
Throws if weights are not same.
Parameters
rhs : in : The object to be added.
References enh::WeightedField< integral, field_c >::saveAdd().
operator+=() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::operator+= (value_type rhs) inline constexpr
operator overloaded to add and save.
Return
Returns reference to current object.
Parameters
rhs : in : The value to be added.
References enh::WeightedField< integral, field_c >::saveAdd().
operator-=() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::operator-= (const WeightedField< value_type, fieldCount > & rhs) inline constexpr
subtracts parameter from object.
Return
Sum of current object and paramater.
Exception
Throws if weights are not same.
Parameters
rhs : in : The object to be subtracted.
References enh::WeightedField< integral, field_c >::saveSub().
operator-=() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::operator-= (value_type rhs) inline constexpr
operator overloaded to subtract and save.
Return
Returns reference to current object.
Parameters
rhs : in : The value to be subtracted.
References enh::WeightedField< integral, field_c >::saveSub().
operator/=()
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::operator/= (value_type divisor) inline constexpr
Sets current object to quotient of current object devided by value with a weight of 1.
Return
Returns reference to current object.
Parameters
divisor : in : The number to be divided by.
References enh::WeightedField< integral, field_c >::saveDiv().
operator<() [1/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator< (const WeightedField< value_type, fieldCount > & rhs) const inline constexpr
Checks whether object is less than parameter.
Return
True if lhs less than rhs.
Exceptions
Throws if they dont have same weights.
Parameters
rhs : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::weightCount.
operator<() [2/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator< (value_type val) const inline constexpr noexcept
Checks whether object is less than parameter.
Return
True if lhs less than rhs.
Parameters
val : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw().
operator<=() [1/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator<= (const WeightedField< value_type, fieldCount > & rhs) const inline constexpr
Checks whether object is less than or equal to parameter.
Return
True if lhs less than or equal to rhs.
Exceptions
Throws if they dont have same weights.
Parameters
rhs : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::weightCount.
operator<=() [2/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator<= (value_type val) const inline constexpr noexcept
Checks whether object is less than or equal to parameter.
Return
True if lhs less than or equal to rhs.
Parameters
val : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw().
operator==() [1/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator== (const WeightedField< value_type, fieldCount > & rhs) const inline constexpr noexcept
Checks whether object is equal to parameter.
Weights must be same as well.
Return
True if lhs equal to rhs.
Parameters
rhs : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::weightCount.
operator==() [2/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator== (value_type val) const inline constexpr noexcept
Checks whether object is equal to parameter.
Return
True if lhs equal to rhs.
Parameters
val : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw().
operator>() [1/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator> (const WeightedField< value_type, fieldCount > & rhs) const inline constexpr
Checks whether object is greater than parameter.
Return
True if lhs greater than rhs.
Exceptions
Throws if they dont have same weights.
Parameters
rhs : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::weightCount.
operator>() [2/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator> (value_type val) const inline constexpr noexcept
Checks whether object is greater than parameter.
Return
True if lhs greater than rhs.
Parameters
val : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw().
operator>=() [1/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator>= (const WeightedField< value_type, fieldCount > & rhs) const inline constexpr
Checks whether object is greater than or equal to parameter.
Return
True if lhs greater than or equal to rhs.
Exceptions
Throws if they dont have same weights.
Parameters
rhs : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::weightCount.
operator>=() [2/2]
template<class integral , unsigned field_c> constexpr bool enh::WeightedField< integral, field_c >::operator>= (value_type val) const inline constexpr noexcept
Checks whether object is greater than or equal to parameter.
Return
True if lhs greater than or equal to rhs.
Parameters
val : in : Value to compare with.
References enh::WeightedField< integral, field_c >::getRaw().
saveAdd() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveAdd (const WeightedField< value_type, fieldCount > & rhs) inline constexpr
Adds parameter to current object.
Return
Reference to current object.
Exception
Throws if weights are not same.
Parameters
rhs : in : The object to be added.
References enh::WeightedField< integral, field_c >::getRaw(), enh::WeightedField< integral, field_c >::saveAdd(), and enh::WeightedField< integral, field_c >::weightCount.
saveAdd() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveAdd (value_type val) inline constexpr noexcept
Adds raw value to current objects.
Return
Returns the sum.
Parameters
val : in : The value to be added.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::setRawValue().
saveAddu() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveAddu (const WeightedField< value_type, fieldCount > & rhs, value_type type_max = std::numeric_limits<value_type>::max()) inline constexpr
Adds parameter to object with no overflow or underflow.
Return
The Reference to current object.
Parameters
rhs : in : The value to be added.
type_max : in : The maximum value for the value_type.
References enh::WeightedField< integral, field_c >::getRaw(), enh::WeightedField< integral, field_c >::saveAddu(), and enh::WeightedField< integral, field_c >::weightCount.
saveAddu() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveAddu (value_type val, value_type type_max = std::numeric_limits<value_type>::max()) inline constexpr noexcept
Adds parameter to object with no overflow or underflow.
Return
The Reference to current object.
Parameters
val : in : The value to be added.
type_max : in : The maximum value for the value_type.
References enh::WeightedField< integral, field_c >::getRaw(), enh::WeightedField< integral, field_c >::saveSubu(), and enh::WeightedField< integral, field_c >::setRawValue().
saveDiv()
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveDiv (value_type divisor) inline constexpr
Sets current object to quotient of current object devided by value with a weight of 1.
Return
Returns reference to current object.
Parameters
divisor : in : The number to be divided by.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::setRawValue().
saveMult()
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveMult (value_type multiplier) inline constexpr noexcept
multiplies current object with value with a weight of 1.
Return
Returns reference to current objects.
Parameters
multiplier : in : The number to be multiplied by.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::setRawValue().
saveSub() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveSub (const WeightedField< value_type, fieldCount > & rhs) inline constexpr
subtracts parameter from object.
Return
Sum of current object and paramater.
Exception
Throws if weights are not same.
Parameters
rhs : in : The object to be subtracted.
References enh::WeightedField< integral, field_c >::getRaw(), enh::WeightedField< integral, field_c >::saveSub(), and enh::WeightedField< integral, field_c >::weightCount.
saveSub() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveSub (value_type val) inline constexpr noexcept
Returns difference of raw value and current object.
Return
Returns the difference.
Parameters
val : in : The value to be subtracted.
References enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::setRawValue().
saveSubu() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveSubu (const WeightedField< value_type, fieldCount > & rhs, value_type type_max = std::numeric_limits<value_type>::max()) inline constexpr
subtracts parameter with no overflow or underflow.
Return
Reference to current object.
Parameters
rhs : in : The value to be subtracted.
type_max : in : The maximum value for the value_type.
References enh::WeightedField< integral, field_c >::getRaw(), enh::WeightedField< integral, field_c >::saveSubu(), and enh::WeightedField< integral, field_c >::weightCount.
saveSubu() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount>& enh::WeightedField< integral, field_c >::saveSubu (value_type val, value_type type_max = std::numeric_limits<value_type>::max()) inline constexpr noexcept
subtracts parameter with no overflow or underflow.
Return
Reference to current object.
Parameters
val : in : The value to be subtracted.
type_max : in : The maximum value for the value_type.
References enh::WeightedField< integral, field_c >::getRaw(), enh::WeightedField< integral, field_c >::saveAddu(), and enh::WeightedField< integral, field_c >::setRawValue().
setRawValue()
template<class integral , unsigned field_c> constexpr void enh::WeightedField< integral, field_c >::setRawValue (value_type val) inline constexpr noexcept
Sets the raw value (compounded weighted sum)
Parameters
val : in : The value to set.
setValue() [1/2]
template<class integral , unsigned field_c> constexpr void enh::WeightedField< integral, field_c >::setValue (const std::array< value_type, fieldCount > & val) inline constexpr noexcept
Sets value to compounded weighted sum of given values.
Parameters
val : in : The values for each field.
setValue() [2/2]
template<class integral , unsigned field_c> constexpr void enh::WeightedField< integral, field_c >::setValue (std::array< value_type, fieldCount > val, std::array< unsigned, weightCount > weight) inline constexpr noexcept
Sets weights and value.
Throws std::invalid_argument if invalid weights are provided.
Parameters
val : in : The values for each field.
weight : in : The weights to set.
References enh::WeightedField< integral, field_c >::setValue(), and enh::WeightedField< integral, field_c >::setWeights().
setWeights()
template<class integral , unsigned field_c> constexpr void enh::WeightedField< integral, field_c >::setWeights (std::array< unsigned, weightCount > weight) inline constexpr noexcept
Sets weights to given weights.
Throws std::invalid_argument if invalid weights are provided.
Parameters
weight : in : The weights to set.
sub() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::sub (const WeightedField< value_type, fieldCount > & rhs) const inline constexpr
Returns sum of current object and parameter.
Return
Sum of current object and paramater.
Exception
Throws if weights are not same.
Parameters
rhs : in : The object to be subtracted.
References enh::WeightedField< integral, field_c >::getRaw(), enh::WeightedField< integral, field_c >::sub(), and enh::WeightedField< integral, field_c >::weightCount.
sub() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::sub (value_type val) const inline constexpr noexcept
Returns difference of raw value and current object.
Return
Returns the difference.
Parameters
val : in : The value to be subtracted.
References enh::WeightedField< integral, field_c >::getRaw().
subu() [1/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::subu (const WeightedField< value_type, fieldCount > & rhs, value_type type_max = std::numeric_limits<value_type>::max()) const inline constexpr
Returns difference with no overflow or underflow.
Return
The difference between current object and parameter.
Parameters
rhs : in : The value to be subtracted.
type_max : in : The maximum value for the value_type.
References enh::WeightedField< integral, field_c >::getRaw(), enh::WeightedField< integral, field_c >::subu(), and enh::WeightedField< integral, field_c >::weightCount.
subu() [2/2]
template<class integral , unsigned field_c> constexpr WeightedField<value_type, fieldCount> enh::WeightedField< integral, field_c >::subu (value_type val, value_type type_max = std::numeric_limits<value_type>::max()) const inline constexpr noexcept
Returns difference with no overflow or underflow.
Return
The difference between current object and parameter.
Parameters
val : in : The value to be subtracted.
type_max : in : The maximum value for the value_type.
References enh::WeightedField< integral, field_c >::addu(), enh::WeightedField< integral, field_c >::getRaw(), and enh::WeightedField< integral, field_c >::sub().
The documentation for this class was generated from the following file:
F:/source/enhance-develop/src/Header/WeightedField.enh.h